# -*- coding: utf-8 -*-
"""book_sales_data_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OMQBnjK-XcR-U8Zd4sK3DzNSUj8ASQJf
"""

startlist = input("Please enter the book database: ")
listsplitfromdollars = startlist.split("$")
flag = True
for allinfoofbook in listsplitfromdollars:
  for allinfoofbook in listsplitfromdollars:
    listee = allinfoofbook.split(",")
    if len(listee) != 4:
      print("Length mismatch in the entries!")
      flag = False
      break
  if(flag == False):
    break
  startlist = startlist.replace("$",",")
  bookallinfolist = startlist.split(",")
  booknameslist = bookallinfolist[0::4]
  for bookname in booknameslist:
    if booknameslist.count(bookname)!= 1:
      print("There are duplicated items in the given database!")
      flag = False
      break
  if(flag == False):
    break
  print("""Please select an option:
1) Display an author's average book sales
2) Display the book with the highest sales
3) Display the year that saw the greatest number of books published """)
  optionchosen = input("Please enter your choice: ")
  if optionchosen != "1" and optionchosen != "2" and optionchosen != "3":
    print("Invalid option!")
    break
  else:
    if optionchosen == "1":
      authorname = input("Please enter an author name: ")
      saleslist = bookallinfolist[3::4]
      authornameslist = bookallinfolist[1::4]
      if authorname in authornameslist:
        bookcount = authornameslist.count(authorname)
        totalsales = 0
        count = 0
        for i in range(len(authornameslist)):
          if authornameslist[i] == authorname:
            salesinnumber = int(saleslist[i])
            totalsales += salesinnumber
            count += 1
            if count == bookcount:
              break
        averageperbook = totalsales/bookcount
        averageperbook = format(averageperbook, ".2f")
        print("Avg. sales per book by", authorname, "is", str(averageperbook))
        break
      else:
        print(authorname, "does not appear in the given database!")
      break
    if optionchosen == "2":
      saleslist = bookallinfolist[3::4]
      maxsale = 0
      for idx in range(len(saleslist)):
        if int(saleslist[idx]) > maxsale:
          maxsale = int(saleslist[idx])
          bestseller = booknameslist[idx]
      print("The book with the all-time highest sales is", bestseller)
      break
    if optionchosen == "3":
      releasedatelist = bookallinfolist[2::4]
      maxcount = 0
      maxcountyear = releasedatelist[0]
      for year in releasedatelist:
        yearcount = releasedatelist.count(year)
        if yearcount > maxcount:
          maxcount = yearcount
          maxcountyear = year
      print("The year that saw the greatest number of books published is", maxcountyear, "with", str(maxcount), "books in total")
      break

1