# -*- coding: utf-8 -*-
"""user_authenticator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PsHZ5b5PIFfNfsDJNa8Bow7_6JgnC4h4
"""

names_scrambled = input("Please enter usernames and passwords: ")
dateslist = input("Please enter last modification information: ")
dates_split = dateslist.split(";")
names_split = names_scrambled.split(";")
if len(dates_split) == len(names_split):
  username = input("Please enter the username: ")
  names_scr = names_scrambled.replace(":",";")
  names_scr = names_scr.split(";")
  if username in names_scr:
    password = input("Please enter the password: ")
    for letter in password:
      index = len(password)
      reversed_password = ""
      for letter in password:
        reversed_password = reversed_password + password[index - 1]
        index = index - 1
    scrambled_password = username[0] + reversed_password + username[1:]
    if scrambled_password in names_scr:
      names_scr = names_scr[1::2]
      indexscrambled = names_scr.index(scrambled_password)
      indexscrambled = int(indexscrambled)
      lastmod_date = dates_split[indexscrambled]
      indexy = lastmod_date.find("y")
      indexm = lastmod_date.find("m")
      indexspace = lastmod_date.find(" ")
      years = int(lastmod_date[:indexy])
      months = int(lastmod_date[indexspace + 1:indexm])
      years = years * 12
      timeinmonths = years + months
      if timeinmonths >= 6:
        print("It has been more than 6 months since your last password update!")
        print("Successful login")
      else:
        print("Successful login")
    else:
      print("Wrong password")
  else:
    print("Wrong username")
else:
  print("List length mismatch!")